LevelFive/LevelFive/urls.py
from django.contrib import admin
from django.urls import path, include
from fiveApp import views

urlpatterns = [
    path('', views.index, name='index'),
    path("admin/", admin.site.urls),
    path('fiveApp/', include('fiveApp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

LevelFive/fiveApp/urls.py
from django.urls import path
from fiveApp import views

# TEMPLATE URLs
app_name = 'fiveApp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

LevelFive/fiveApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # blank True means that field can be left blank
    portfolio_site = models.URLField(blank=True)
    portfolio_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

LevelFive/fiveApp/forms.py
from django import forms
from django.contrib.auth.models import User
from fiveApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'portfolio_pic')

LevelFive/fiveApp/views.py
from django.shortcuts import render
from fiveApp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context_dict = {"name":"Dipti"}
    return render(request, 'fiveApp/index.html', context_dict)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("Hey! You are logged in!")


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,
            'fiveApp/registration.html',
            {'user_form':user_form,
            'profile_form':profile_form,
            'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("This account is not Active!")
        else:
            print("Someone tried to login and failed")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request,'fiveApp/login.html',{})

LevelFive/templates/fiveApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
    <title>Level Five</title>
  </head>
  <body>
    <nav class = 'navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'index' %}">LevelApp</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'fiveApp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class='navbar-link' href="{% url 'fiveApp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body-block %}
      {% endblock %}
    </div>

  </body>
</html>

LevelFive/templates/fiveApp/index.html
<!DOCTYPE html>
{% extends 'fiveApp/base.html' %}
{% block body-block %}
<div class="jumbotron">
  <h1>Django Level Five .. index</h1>
</div>
{% endblock %}

LevelFive/templates/fiveApp/login.html
<!DOCTYPE html>
{% extends 'fiveApp/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Django Level Five .. login</h1>
</div>
{% endblock %}

LevelFive/templates/fiveApp/registration.html
{% extends 'fiveApp/base.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  <h1>register</h1>
  {% if registered %}
    <h1>Thank you for registering!!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Please fill the form:</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" value="register">
    </form>
  {% endif  %}
</div>
{% endblock %}